<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>mvp_conf_2026</RootNamespace>
        <AssemblyName>TodoList.Layered</AssemblyName>
        <Company>TodoList.Layered</Company>
        <Product>TodoList.Layered</Product>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12"/>
    </ItemGroup>

</Project>
